### ISSUE TITLE
The manually created storageclass is deleted by virtual cluster

### ISSUE THREAD

**Issue by wangjsty** [kubernetes-sigs/cluster-api-provider-nested#176]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

I created a most simple storage class in virtual cluster by the following yaml:
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```
```console
# oc get sc
NAME            PROVISIONER                    AGE
local-storage   kubernetes.io/no-provisioner   8s
```
After about 1 minute
```console
# oc get sc
No resources found in default namespace.
```

**What did you expect to happen:**
The storage is available there.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I also tried other type storage class, such as local-path-storageclass, nfs-storageclass, the problem is same.

But if I created the same type and name storage class in super cluster, the problem can be resolved. Is it a bug? or it just work as design. Thanks. 

**Environment:**

- cluster-api-provider-nested version: Built from main branch
- Minikube/KIND version: OpenShift 4.7.13
- Kubernetes version: (use `kubectl version`): 1.20.0
- OS (e.g. from `/etc/os-release`): Red Hat Enterprise Linux 8

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-provider-nested/labels?q=area for the list of labels]
