### ISSUE TITLE
Not allow edit virtualcluster for some field 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-nested#184]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

**What did you expect to happen:**

```
kubectl edit vc vc-sample-23

spec:
  clusterDomain: cluster.local
  clusterVersionName: cv-sample-np23 ===> cv-sample-np24
```

success 

expected: it should fail, we should consider only allow desired field to be updated and block others ..

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-nested version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-provider-nested/labels?q=area for the list of labels]
