### ISSUE TITLE
Support exposing single annotations/labels via env downward API

### ISSUE THREAD

**Issue by wondywang** [kubernetes-sigs/cluster-api-provider-nested#297]
**User Story**

As a developer, I would like VirtualCluster to support exposing annotations/labels via env downward API. 

**Detailed Description**
For example:
```yaml
containers:
  - env:
    - name: LABEL_KEY
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels['label1']
    - name: ANNO_KEY
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations['anno1']
```
The fieldRef used for that will sync to the super cluster.

**Anything else you would like to add:**

More information about this issue: [#31218](https://github.com/kubernetes/kubernetes/issues/31218)

/kind feature
