### ISSUE TITLE
Pod DWS support container Commands&Args  update

### ISSUE THREAD

**Issue by wondywang** [kubernetes-sigs/cluster-api-provider-nested#320]
**User Story**

As a user I would like to both change container image.name and commands. But i found that Pod DWS sync only image.name, except commands.  Maybe sometimes, it is possible that the startup parameters of the image also need to be changed synchronously.

**Detailed Description**

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: command-demo
spec:
  containers:
  - name: command-demo-container
    image: debian
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]
```

Pod DWS should support container Commands&Args update also.

/kind feature
